Develop
veg/hyphy pull request #1677
Opened 2024-01-08 14:37 UTC by spond

2024-01-08 21:11 UTC, stevenweaver commented on src/core/tree.cpp
> +    //unsigned long id;
This line should be removed.

2024-01-08 21:18 UTC, stevenweaver requested changes

2024-01-08 21:19 UTC, stevenweaver commented
2.5.59 tag should be removed because it appears that this PR was intended to be merged into `master` beforehand.

2024-01-08 23:42 UTC, spond commented on res/TemplateBatchFiles/SelectionAnalyses/error-filter.bf
> +
That's my bad habit of leaving debugging code as comments :(

2024-01-08 23:52 UTC, spond commented on res/TemplateBatchFiles/SelectionAnalyses/error-filter.bf
> +
Changes made as requested.

2024-01-08 23:53 UTC, spond commented on src/core/formula.cpp
> +                    /*if (used_float_slots == available_slots) {
Changes made as requested.

2024-01-08 23:53 UTC, spond commented on src/core/formula.cpp
> +hyFloat _Formula::ComputeSimple (_SimpleFormulaDatum* stack, _SimpleFormulaDatum* varValues, long allocate_local) {
Changes made as requested.

2024-01-08 23:53 UTC, spond commented
Change requests should be resolved.

2024-01-09 00:37 UTC, stevenweaver approved these changes

2024-01-09 00:37 UTC, merged